name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: gitleaks/gitleaks-action@v2
      continue-on-error: true

    - name: Dummy Deploy
      run: |
        echo "Starting dummy deploy..."
        sleep 3
        echo "Deploy successful! 🎉 (Just a dummy deploy)"
