name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Run Gitleaks
      uses: gitleaks/gitleaks-action@v2.3.4
      with:
        args: "detect --report-format sarif --report-path gitleaks-results.sarif"

    - name: Upload Gitleaks SARIF
      uses: actions/upload-artifact@v4
      with:
        name: gitleaks-results
        path: gitleaks-results.sarif
